apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vault-ha-discovery
  namespace: {{.Release.Namespace}}
  labels:
    app.kubernetes.io/name: {{.Chart.Name}}
    app.kubernetes.io/instance: {{.Release.Name}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vault-ha-discovery
subjects:
  - kind: ServiceAccount
    name: {{.Release.Name}}
    namespace: {{.Release.Namespace}}
