apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vault-ha-discovery
  namespace: {{.Release.Namespace}}
  labels:
    app.kubernetes.io/name: {{.Chart.Name}}
    app.kubernetes.io/instance: {{.Release.Name}}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list", "update", "patch"]
