apiVersion: v1
kind: Secret
metadata:
  name: tls-certs
  namespace: {{.Release.Namespace}}
  labels:
    app.kubernetes.io/name: {{.Chart.Name}}
    app.kubernetes.io/instance: {{.Release.Name}}
type: kubernetes.io/tls
data:
  tls.ca: {{.Files.Get "config/tls.ca" | b64enc}}
  tls.crt: {{.Files.Get "config/tls.crt" | b64enc}}
  tls.key: {{.Values.vault_tls_key}}

---
apiVersion: v1
kind: Secret
metadata:
  name: tls-ca
  namespace: {{.Release.Namespace}}
  labels:
    app.kubernetes.io/name: {{.Chart.Name}}
    app.kubernetes.io/instance: {{.Release.Name}}
type: Opaque
data:
  ca.crt: {{.Files.Get "config/tls.ca" | b64enc}}
